#!/usr/bin/python3

from PyQt5.QtWidgets import (QWidget, QGridLayout, QCheckBox, QPushButton, QApplication,
                             QHBoxLayout, QVBoxLayout, QLabel,
                             QLineEdit, QSpinBox, QGroupBox,
                             QRadioButton, QToolButton, QFileDialog,
                             QMessageBox)
from PyQt5.QtCore import QCoreApplication, pyqtSlot
from PyQt5.QtGui import QIcon
import sys
import os.path
import subprocess
from shutil import which


class Form(QWidget):
    def __init__(self):
        super().__init__()
    
        self.crawlButton = QPushButton("Crawl")
        self.crawlButton.clicked.connect(self.begin_crawl)
        self.quitButton = QPushButton("Quit")
        self.quitButton.clicked.connect(QCoreApplication.instance().quit)
        self.buttonLabel = QLabel("Buttons")
        
        self.hbox1 = QHBoxLayout()
        self.hbox1.setSpacing(5)
        self.hbox1.addStretch(1)
        self.hbox1.addWidget(self.crawlButton)
        self.hbox1.addWidget(self.quitButton)
        
        self.siteLabel = QLabel("Tumblr Name")
        self.siteLabel.setToolTip("Name of the site without <i>.tumlr.com</i>.")
        self.siteEdit = QLineEdit()
        self.suffixLabel = QLabel("<i>.tumblr.com</i>")
        
        self.hbox2 = QHBoxLayout()
        self.hbox2.setSpacing(4)
        self.hbox2.addWidget(self.siteEdit)
        self.hbox2.addWidget(self.suffixLabel)
        
        self.histLabel = QLabel("History")
        self.allCheck = QCheckBox("All")
        self.allCheck.clicked.connect(self.history_wanted)
        self.allCheck.setChecked(True)
        self.monthLabel1 = QLabel("Only last")
        self.monthLabel1.setEnabled(False)
        self.monthLabel2 = QLabel("Months")
        self.monthLabel2.setEnabled(False)
        self.monthLabel1.setToolTip("Only go back this many months.")
        self.monthSpin = QSpinBox()
        self.monthSpin.setRange(1, 72)
        self.monthSpin.setValue(1)
        self.monthSpin.setEnabled(False)
        
        self.hboxmonths = QHBoxLayout()
        self.hboxmonths.setSpacing(4)
        self.hboxmonths.addWidget(self.monthLabel1)
        self.hboxmonths.addWidget(self.monthSpin)
        self.hboxmonths.addWidget(self.monthLabel2)

        self.wantedLabel = QLabel("Media Wanted")
        self.wantedGroup = QGroupBox()
        self.wantedGroup.setToolTip("Get photos and videos, just photos, or just videos")
        self.allRadio = QRadioButton("Both")
        self.photoRadio = QRadioButton("Photos")
        self.videoRadio = QRadioButton("Videos")
        self.allRadio.setChecked(True)
        self.hboxGroup = QHBoxLayout()
        self.hboxGroup.addWidget(self.allRadio)
        self.hboxGroup.addStretch(1)
        self.hboxGroup.addWidget(self.photoRadio)
        self.hboxGroup.addStretch(1)
        self.hboxGroup.addWidget(self.videoRadio)
        self.wantedGroup.setLayout(self.hboxGroup)
        
        self.destLabel = QLabel("Save Path")
        self.destEdit = QLineEdit(os.path.expanduser("~") + "/Downloads")
        self.destTButton = QToolButton()
        
        self.hbox4 = QHBoxLayout()
        self.hbox4.addWidget(self.destEdit)
        self.hbox4.addWidget(self.destTButton)
        self.toolIcon = QIcon.fromTheme("folder")
        self.destTButton.setIcon(self.toolIcon)
        self.destTButton.clicked.connect(self.getDownloadPath)
        
        self.vbox0 = QVBoxLayout()
        self.vbox0.setSpacing(20)

        self.grid = QGridLayout()
        self.grid.setVerticalSpacing(12)
        self.grid.setHorizontalSpacing(52)
        self.grid.addWidget(self.siteLabel, 1, 1)
        self.grid.addLayout(self.hbox2, 1, 2, 1, 3)
        self.grid.addWidget(self.histLabel, 2, 1)
        self.grid.addWidget(self.allCheck, 2, 2)
        self.grid.addLayout(self.hboxmonths, 2, 3, 1, 2)
        self.grid.addWidget(self.wantedLabel, 3, 1)
        self.grid.addWidget(self.wantedGroup, 3, 2, 1, 3)
        self.grid.addWidget(self.destLabel, 4, 1)
        self.grid.addLayout(self.hbox4, 4, 2, 1, 3)
        
        self.vbox0.addLayout(self.grid)
        self.vbox0.addLayout(self.hbox1)

        self.setLayout(self.vbox0)
        self.setWindowTitle("TumblrCrawler v2")
        self.setWindowIcon(QIcon('/usr/share/icons/hicolor/256x256/apps/tumblrcrawl.png'))
        self.show()
    
    @pyqtSlot()
    def history_wanted(self):
        if self.allCheck.isChecked():
            self.monthSpin.setEnabled(False)
            self.monthLabel1.setEnabled(False)
            self.monthLabel2.setEnabled(False)
        else:
            self.monthSpin.setEnabled(True)
            self.monthLabel1.setEnabled(True)
            self.monthLabel2.setEnabled(True)


    @pyqtSlot()
    def begin_crawl(self):
        if self.siteEdit.text() == "":
            QMessageBox.warning(self, "Missing Name",
                    "You must enter a site name to crawl.")
            return 
        if not os.path.exists(self.destEdit.text()):
            QMessageBox.warning(self, "Bad Directory",
                    "The given save path cannot be found.")
            return
        
        if not which('tumblrcrawl.py'):
            QMessageBox.critical(self, "Crawler Not Found",
                    "tumblrcrawl.py is missing. Check your installation.")
            return 
        
        if which('konsole'):
            terminal = 'konsole'
        elif which('urxvt'):
            terminal = 'urxvt'
        elif which('xterm'):
            terminal = 'xterm'
        else:
            QMessageBox.critical(self, "No Terminal", "No usable terminals were found.")
            return
        
        cmd = [terminal]
        cmd.append("-title")
        cmd.append("tumblrcrawl")
        cmd.append("-e")
        cmd.append("tumblrcrawl.py")
        cmd.append(self.siteEdit.text())
        cmd.append(str(self.monthSpin.value()))
        
        if self.photoRadio.isChecked():
            cmd.append("p")
        elif self.videoRadio.isChecked():
            cmd.append("v")
        
        cmd.append("X-DIR" + self.destEdit.text())
        cmd.append("h")
        
        print(cmd)
        #subprocess.Popen(cmd)
    
    @pyqtSlot()
    def getDownloadPath(self):
        where = QFileDialog.getExistingDirectory(self, "Choose", self.destEdit.text())
        #where.setFileMode(QFileDialog.DirectoryOnly)
        if where:
            self.destEdit.setText(where)


if __name__ == '__main__':
    app = QApplication(sys.argv)
    f = Form()
    sys.exit(app.exec_())
